# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: registry-1.docker.io/amankinenko/python-flask-sample-app-test1
  tag: 67a06085bec2e2fe2a9b72a8
service:
  name: python
  type: LoadBalancer
  externalPort: 80
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
